language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - travis
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAW3FERPLDPF55B36Z
  secret_access_key:
    secure: O9d7fSZX4sdk5PmcEfOnIdAjk5AGDklydOxX9Jkm6/YgfE8Fn7btHYnPORPqLsPofa5mmR8bBHKIpfozvfNJF2ObLiP3p2MQvN+HKPsVdtXNKGtyekAvDtIUxicn8sQQ5vW9KvMF8QVdYCZxXSEIsxRH3RmPwWWybHmyj6AkIVQ=
  bucket: assets.api.bible
  local-dir: dist
  on:
    repo: americanbible/api-bible-assets
    branch: travis
