language: node_js
node_js:
- stable
branches:
  only:
  - master
  - travis
before_deploy:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAW3FERPLDNAZNWM7C
  secret_access_key:
    secure: Lrdo8pvorslMSikBGvOlVzZZTtAb/Rrn/ljhyKJlw2OuezOOGrK3PmaZiWMbTBhKr0JMBloomb3frm7VeAGf+vvNpfpgGqi7Q09RkShUAPolgqekIkrnHSQ7HLb5CIi2rN+3RLRo9y2Nv+F4Amqe2x7eOQXof/TVDO0cdQE6orA=
  bucket: assets.api.bible
  local-dir: dist
  on:
    branch: travis
