language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - travis
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAW3FERPLDNAZNWM7C
  secret_access_key:
    secure: OxsK8ADaiJGdfES84mjC6ToTSYCNFOk8ubP5+WniZoWgipz+MWoBMBHeq0HDpyVqGdrMFhnhDZs75hvuYz/oRtZQBeghhvIWcA3pIMdbp5gJITgzLXIsYVoSpLQoGPNOCKtvriKJag4UdaDldWfXPRXQYGgA+YdhIocvVO+Adfc=
  bucket: assets.api.bible
  local-dir: dist
  acl: public_read
  on:
    repo: americanbible/api-bible-assets
    branch: travis
