language: node_js
node_js:
  - 11
branches:
  only:
    - master
    - travis
before_deploy:
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      repo: americanbible/scripture-styles
      branch: master
  - provider: s3
    access_key_id: AKIAW3FERPLDGBJYGAJE
    secret_access_key:
      secure: ELmpNQplp88y3HUkwbyjhz0VR02XkLRlHjGbW0/Vf4ipuEIsFgNK+jRayW18C9J/QhewG9BTyv+ZcgY2MAoxyc4Qd5dReaOvk6K2enacCZbx1ClSkyaTTmBox3u6cknFB/3nwOuyywW/+1yTXUX+6j1mMjABw6tFLgd8P1Cy3MM=
    bucket: assets.api.bible
    local-dir: dist
    on:
      repo: americanbible/scripture-styles
      branch: master
  - provider: script
    skip_cleanup: true
    script: cd previewer && npm run deploy-storybook -- --ci
    on:
      repo: americanbible/scripture-styles
      branch: master
