language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - travis
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAW3FERPLDPF55B36Z
  secret_access_key:
    secure: VA9xlKBg39se98B5eIpzZrNgDdguKTX+uoKrxa8r3oZfrcLgZqmocwTNEHRppA8B8P/h8JENDX2qyoDPpS5WedgU+fUilJfQctGSTG20+yv7cKqv+k9P8xUN/HnBaMHC++OPQnEPkou+PN0pCFrh75x29x2zyiofqQFkeEsPYyc=
  bucket: assets.api.bible
  local-dir: dist
  on:
    repo: americanbible/api-bible-assets
    branch: travis
