language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - travis
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAW3FERPLDL6MEIMPF
  secret_access_key:
    secure: NqsO6CyOBbjcVIum+n7KuEUmmsBXTrMKExzr8qAxm/YS0jR4DAbaCe78JscgyhBoU+hpKkgcVB/7BgpgSOOJv2P8zRCHH2C5DRBe78tGnv4ifQ4UXbQG1OtnQFvDCqUH4NpdPRG+Sya/8UzLduLFqt01mADOGNIPll93GMZMYUo=
  bucket: assets.api.bible
  local-dir: dist
  on:
    branch: travis
