language: node_js
node_js:
- 11
branches:
  only:
  - master
  - travis
before_deploy:
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    repo: americanbible/scripture-styles
    branch: master
# - provider: s3
#   access_key_id: AKIAW3FERPLDNJJQOFU7
#   secret_access_key:
#     secure: aU9oddW2jCxVGkoRNdSaD7KD1fQjUUsL6Xz18VJosfFzs7mUJy/GiPT03bvw6jD4lnYbexA9bZGYMaPlxUpIW4i6FQFusckQSRvBt520nhI7LW343GyfZ6E/eBy7vI5jvrqkyj3/S8FYBZJMk8L1vQOCaOLZm1neRDiXKn+GMTI=
#   bucket: assets.api.bible
#   local-dir: dist
#   acl: public_read
#   on:
#     repo: americanbible/scripture-styles
- provider: script
  skip_cleanup: true
  script: cd previewer && npm run deploy-storybook -- --ci
  on:
    repo: americanbible/scripture-styles
    branch: master

