language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - travis
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAW3FERPLDL6MEIMPF
  secret_access_key: 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
  bucket: assets.api.bible
  region: "us-east-1"
  local-dir: dist
  on:
    branch: travis
